### ISSUE TITLE
Please dissassociate this with the Enmap name

### ISSUE THREAD

**Issue by eslachance** [MierenManz/D-Enmap#1]
While I don't have any trademark associate with the name Enmap, as the owner of that module, I'd prefer this code not be associated with me and my Enmap module in any way. This isn't a Deno port, it's not even *close* to it. 

And, I'm not saying this code is bad at all - in fact I applaud the work you put in it. It's just not an "enhanced map" in any way. It also has very different usage and methods, and it's not synchronous as Enmap is.

Please, if you respect Enmap enough to want to use the name, I'd ask that you'd extend that respect to not using it. Please choose a name that is not derivative or related to Enmap.

**Comment by MierenManz** [comment]
I would use a different name if I had one for it :|
If you have any suggestions, let me know

**Comment by eslachance** [comment]
Well, here's a few ideas: 

- BaseData (node => deno, database => basedata)
- EzDb (lame, I know)
- DenoBase
- StowRage (meh, it's a pun)
- Stowaway (previous one inspired me, it's cute)

I'll let you brainstorm for variance, personally I think I like Stowaway <3

**Comment by MierenManz** [comment]
I think I'll go with stowaway, thank you for the suggestion :D
